/**
 * Glossary + lesson catalog (paraphrase of knowledge/16). Keep units short for UI.
 */
import type { GlossaryEntry, LessonCard, SourceCitation } from './types'

const bam = (detail: string): SourceCitation => ({
  sourceId: 'bam1980',
  label: '1980 Arranging Manual',
  detail,
})
const ryl = (detail: string): SourceCitation => ({
  sourceId: 'rylander',
  label: 'Rylander 11 chords',
  detail,
})
const pri = (detail: string): SourceCitation => ({
  sourceId: 'prietto',
  label: 'Prietto practice guide',
  detail,
})
const fea = (detail: string): SourceCitation => ({
  sourceId: 'feasibility',
  label: 'Product limits',
  detail,
})

export const GLOSSARY: readonly GlossaryEntry[] = [
  {
    id: 'pillar',
    term: 'Pillar',
    short:
      'A primary harmonic destination under a stretch of melody — what the phrase is “about,” not every decorative chord.',
    citations: [bam('Approach Two'), pri('harmonic pillars')],
  },
  {
    id: 'pmn',
    term: 'PMN',
    short: 'Primary melody note — structural / stressed; should belong to the pillar harmony.',
    citations: [bam('Approach Two labels')],
  },
  {
    id: 'smn',
    term: 'SMN',
    short: 'Secondary melody note — connective; may use color or passing chords.',
    citations: [bam('Approach Two labels')],
  },
  {
    id: 'pcf',
    term: 'PCF',
    short: 'Primary chord family — chords built on the current pillar root.',
    citations: [bam('Approach Two')],
  },
  {
    id: 'scf',
    term: 'SCF',
    short: 'Secondary chord family — Groups 1–6 of passing roots related to the pillar.',
    citations: [bam('Approach Two Step V')],
  },
  {
    id: 'bs7',
    term: 'Barbershop seventh',
    short:
      'Dominant-quality seventh with a harmonic (flat) 7th — the classic lock-and-ring four-note chord.',
    citations: [ryl('BS7 ratios'), pri('style building blocks')],
  },
  {
    id: 'lock_ring',
    term: 'Lock & ring',
    short: 'Overtone reinforcement when intervals are just — the “buzz” contest charts chase.',
    citations: [ryl('core idea'), pri('lock & ring')],
  },
  {
    id: 'circle_fifths',
    term: 'Circle of fifths',
    short: 'Descending-fifth root motion is the barbershop harmonic highway.',
    citations: [bam('style + Approach Three Rule 1')],
  },
  {
    id: 'springboard',
    term: 'Springboard',
    short: 'I and IV may leap freely; afterward normal progression rules resume.',
    citations: [bam('Approach Three axiom')],
  },
  {
    id: 'secondary_dom',
    term: 'Secondary dominant',
    short: 'A BS7 a fifth above a target that drives into that chord (often the next pillar).',
    citations: [pri('secondary dominants'), bam('Rule 1')],
  },
  {
    id: 'counterpart',
    term: 'Tritone counterpart',
    short: 'Two BS7s a tritone apart share 3↔7 and can swap under the right melody tones.',
    citations: [bam('Approach Three Rule 3')],
  },
  {
    id: 'strong_voicing',
    term: 'Strong voicing',
    short: 'Which chord tone the lead sings — 3rd/7th on dominants often sings stronger than root/5th.',
    citations: [pri('strong voicing')],
  },
  {
    id: 'ttbb',
    term: 'TTBB stack',
    short: 'Tenor above lead; bari may sit above lead when melody is low; bass lowest.',
    citations: [bam('voicing chapter')],
  },
  {
    id: 'ji',
    term: 'Just intonation',
    short: 'Exact frequency ratios (vs equal temperament) used for ear coaching and MIDI bends.',
    citations: [ryl('JI ratios')],
  },
  {
    id: 'homophony',
    term: 'Homophony',
    short: 'Parts change together under the lead — default texture before embellishment.',
    citations: [bam('style'), pri('homophonic pillars')],
  },
  {
    id: 'tension_release',
    term: 'Tension & release',
    short: 'Unstable tones (especially in a BS7) move by step into a resting chord — the V7→I story.',
    citations: [bam('harmony / Approach Three'), pri('tension')],
  },
  {
    id: 'harmonic_series_spacing',
    term: 'Series spacing',
    short: 'Nature’s chord: wider gaps at the bottom, tighter voicing on top for easier lock.',
    citations: [bam('voicing'), pri('spacing')],
  },
  {
    id: 'common_tone',
    term: 'Common tone',
    short: 'A pitch shared by two consecutive chords — often held in the same voice.',
    citations: [bam('voice leading')],
  },
  {
    id: 'contrary_motion',
    term: 'Contrary motion',
    short: 'Outer parts move opposite directions — fuller chord successions.',
    citations: [bam('voice leading')],
  },
  {
    id: 'parallel_5_8',
    term: 'Parallel 5ths/8ves',
    short: 'The same perfect fifth or octave sliding between two parts — can thin the texture.',
    citations: [bam('voice leading')],
  },
  {
    id: 'omit_5',
    term: 'Dom9 omit choice',
    short:
      'Dom9 has five tones → omit one. Prietto/BAM often omit the root (bass on 5th); Rylander often omits the 5th (bass on root). Always keep 3, ♭7, and 9.',
    citations: [pri('Dom9'), ryl('ninth'), bam('voicing')],
  },
  {
    id: 'leading_tone',
    term: 'Leading tone',
    short: 'The 3rd of a dominant (scale degree 7) wants to rise to the tonic.',
    citations: [bam('harmony')],
  },
  {
    id: 'active_seventh',
    term: 'Active seventh',
    short: 'The ♭7 of a dominant wants to fall to the next chord’s 3rd.',
    citations: [bam('harmony')],
  },
  {
    id: 'incomplete_chord',
    term: 'Incomplete chord',
    short: 'Missing structural tones (root / 3rd / 7th on dominants) — complete or repair helpers fill them.',
    citations: [bam('voicing'), pri('complete chords')],
  },
  {
    id: 'roman_analysis',
    term: 'Roman numeral analysis',
    short: 'Label chords by key degree (I ii iii IV V vi vii°) and applied dominants (V7/V, ♭II7, etc.).',
    citations: [bam('harmony'), pri('function')],
  },
]

export const LESSONS: readonly LessonCard[] = [
  {
    id: 'L-done',
    wizardStep: 'done',
    title: 'Done for this pass',
    body: 'Chart complete for this pass. Taste, lyrics, and copyright remain human judgment.',
    glossaryIds: [],
    citations: [fea('human gates')],
  },
  {
    id: 'L-melody',
    wizardStep: 'melody',
    title: 'Lead first',
    body: 'Enter an accurate lead before inventing harmony. The arrangement serves this line; lyrics and story stay human.',
    glossaryIds: ['pmn', 'homophony'],
    citations: [bam('Approach Two prerequisites')],
  },
  {
    id: 'L-step1',
    wizardStep: 'step1_roots',
    title: 'Find primary roots',
    body: 'Hum the simplest bass under the tune. Those notes are candidate pillars — prefer roots over fifths when unsure. Software suggests; your ear confirms.',
    glossaryIds: ['pillar'],
    citations: [bam('Step I')],
  },
  {
    id: 'L-step2',
    wizardStep: 'step2_confirm',
    title: 'Confirm before filling',
    body: 'Cross-check odd root moves, then lock pillars. Unconfirmed pillars mean the chart is still a draft skeleton.',
    glossaryIds: ['pillar'],
    citations: [bam('Step II'), fea('human gate')],
  },
  {
    id: 'L-step3',
    wizardStep: 'step3_pmn_pcf',
    title: 'PMN on PCF',
    body: 'Structural melody notes get chords from the pillar’s primary family. Prefer complete chords and BS7 color when the lead allows.',
    glossaryIds: ['pmn', 'pcf', 'bs7'],
    citations: [bam('Step III')],
  },
  {
    id: 'L-step4',
    wizardStep: 'step4_smn_pcf',
    title: 'SMN still on PCF',
    body: 'Many weaker notes still work as PCF color (6, add9, 7ths). Leftovers that cannot sit on the pillar family wait for SCF.',
    glossaryIds: ['smn', 'pcf', 'scf'],
    citations: [bam('Step IV')],
  },
  {
    id: 'L-step5',
    wizardStep: 'step5_smn_scf',
    title: 'Passing with SCF',
    body: 'Secondary chord families supply legal passing roots that keep the pillar story while covering connective melody.',
    glossaryIds: ['scf', 'pillar'],
    citations: [bam('Step V')],
  },
  {
    id: 'L-step6',
    wizardStep: 'step6_alts',
    title: 'Strengthen the highway',
    body: 'Revisit weak bars; prefer stronger approaches into the next pillar — often a secondary-dominant BS7.',
    glossaryIds: ['secondary_dom', 'bs7', 'circle_fifths'],
    citations: [bam('Step VI')],
  },
  {
    id: 'L-step7',
    wizardStep: 'step7_variety',
    title: 'Ornament last',
    body: 'Swipes and tags decorate a solid block+passing path — they are not a substitute for pillars.',
    glossaryIds: ['pillar', 'homophony'],
    citations: [bam('Step VII')],
  },
  {
    id: 'L-step8',
    wizardStep: 'step8_voicing',
    title: 'Stack and lead',
    body: 'Polish TTBB order, doubles, and muddy clusters. Bari above lead is normal; tenor below lead is not.',
    glossaryIds: ['ttbb', 'strong_voicing'],
    citations: [bam('voicing')],
  },
  {
    id: 'L-step9',
    wizardStep: 'step9_final',
    title: 'Taste and law',
    body: 'Clear hard errors, hear JI lock, export — then human taste, lyrics, and copyright remain yours.',
    glossaryIds: ['ji', 'lock_ring'],
    citations: [bam('Step IX'), fea('human gates')],
  },
  {
    id: 'L-R1',
    ruleTag: 'R1_p5',
    title: 'Circle-of-fifths motion',
    body: 'Roots a fifth apart — especially down a fifth — are the strongest barbershop progression, including secondary dominants into pillars.',
    glossaryIds: ['circle_fifths', 'secondary_dom'],
    citations: [bam('Approach Three Rule 1')],
  },
  {
    id: 'L-R1r',
    ruleTag: 'R1_retro',
    title: 'Retrogression on the circle',
    body: 'Up-a-fifth “backup” can harmonize awkward tones, then resume forward motion toward the pillar.',
    glossaryIds: ['circle_fifths'],
    citations: [bam('Rule 1 retrogression')],
  },
  {
    id: 'L-R2',
    ruleTag: 'R2_chromatic',
    title: 'Chromatic sevenths',
    body: 'Chromatic BS7→BS7 connects melody by half step while staying on ringing sevenths.',
    glossaryIds: ['bs7'],
    citations: [bam('Rule 2')],
  },
  {
    id: 'L-R3',
    ruleTag: 'R3_tritone',
    title: 'Tritone counterparts',
    body: 'BS7s a tritone apart share 3rd/7th and can swap under the right melody tones — carefully at fast tempos.',
    glossaryIds: ['counterpart', 'bs7'],
    citations: [bam('Rule 3')],
  },
  {
    id: 'L-R4',
    ruleTag: 'R4_dim7',
    title: 'Diminished as transition',
    body: 'Dim7 anticipates, holds, or pushes — it is not a long pillar sonority. Escape: lower any tone → BS7 root; raise any tone → m6 (that tone as 5th).',
    glossaryIds: ['pillar'],
    citations: [bam('Rule 4'), ryl('dim7')],
  },
  {
    id: 'L-R5',
    ruleTag: 'R5_m3up',
    title: 'Major-third lift',
    body: 'A BS7 may progress to a root a major third above (classic ♭VI7→I). Prefer a non-seventh target; M3-up into another 7/9 is ranked weaker (often holding/family, not classic R5).',
    glossaryIds: ['bs7'],
    citations: [bam('Rule 5')],
  },
  {
    id: 'L-spring',
    ruleTag: 'springboard',
    title: 'Springboard freedom',
    body: 'From I or IV the harmony may leap; afterward normal progression rules apply again.',
    glossaryIds: ['springboard'],
    citations: [bam('Approach Three axiom')],
  },
  {
    id: 'L-vocab',
    lintRuleId: 'illegal-nature',
    title: 'Contest vocabulary',
    body: 'SAI/Rylander charts stay on eleven ringing chord types. Outside natures break the intended lock vocabulary.',
    glossaryIds: ['bs7', 'lock_ring'],
    citations: [ryl('11 chords'), pri('SAI vocabulary')],
  },
  {
    id: 'L-homophony',
    lintRuleId: 'orphan-stack',
    title: 'Harmony follows the lead',
    body: 'Every stack should sit under a melody onset. Orphans usually mean the lead moved and harmony did not.',
    glossaryIds: ['homophony', 'pmn'],
    citations: [bam('lead-first workflow')],
  },
  {
    id: 'L-ttbb',
    lintRuleId: 'voice-leading',
    title: 'TTBB voice leading',
    body: 'Keep tenor above lead, bass at the bottom, and watch muddy minor seconds between parts.',
    glossaryIds: ['ttbb'],
    citations: [bam('voicing & VL')],
  },
  {
    id: 'L-complete',
    lintRuleId: 'incomplete-triad',
    title: 'Complete the triad',
    body: 'Triads need a clear third (and usually a fifth). Missing chord tones blur the sonority.',
    glossaryIds: ['pcf'],
    citations: [bam('Step III'), pri('complete chords')],
  },
  {
    id: 'L-dom9',
    lintRuleId: 'thin-ninth',
    title: 'Dom9 omit choice',
    body: 'A dominant ninth has five pitch classes. Prietto/BAM often omit the root (bass on 5th); Rylander often omits the 5th (bass on root). Always keep 3, ♭7, and 9.',
    glossaryIds: ['omit_5', 'bs7'],
    citations: [pri('Dom9 voicing'), ryl('ninth')],
  },
  {
    id: 'L-doubles',
    lintRuleId: 'doubled-third',
    title: 'Careful doubles',
    body: 'Doubling the third often weakens a triad; prefer doubling the root on majors/minors.',
    glossaryIds: ['strong_voicing'],
    citations: [ryl('major triad'), bam('Approach Two')],
  },
  {
    id: 'L-aug',
    lintRuleId: 'aug-pillar',
    title: 'Augmented is last resort',
    body: 'Augmented chords are melody-forced color — poor choices as sustained primary pillars.',
    glossaryIds: ['pillar'],
    citations: [ryl('chord 11')],
  },
  {
    id: 'L-secdom',
    lintRuleId: 'few-sevenths',
    title: 'Need some BS7 drive',
    body: 'Long stretches without barbershop sevenths miss classic tension-and-release into pillars.',
    glossaryIds: ['bs7', 'secondary_dom'],
    citations: [pri('secondary dominants'), bam('Strengthen')],
  },
  {
    id: 'L-range',
    lintRuleId: 'lead-range',
    title: 'Singable lead range',
    body: 'If the lead sits outside a comfortable ensemble range, transpose early — before dense harmony locks the key.',
    glossaryIds: ['pillar'],
    citations: [pri('range guidance')],
  },
  {
    id: 'L-ji',
    lintRuleId: 'dull-harmonicity',
    title: 'Ringing intervals',
    body: 'Just ratios favor certain natures and voicings. A dull score means another legal option may lock better.',
    glossaryIds: ['ji', 'lock_ring'],
    citations: [ryl('harmonicity / ratios')],
  },
  {
    id: 'L-strong',
    lintRuleId: 'strong-voicing',
    title: 'Lead chord tone',
    body: 'On dominants, lead as 3rd or 7th often sings stronger than root or fifth.',
    glossaryIds: ['strong_voicing', 'bs7'],
    citations: [pri('strong voicing')],
  },
  {
    id: 'L-law',
    lintRuleId: 'copyright-reminder',
    title: 'Copyright is human',
    body: 'The app can remind you — clearance and licensing stay your responsibility.',
    glossaryIds: [],
    citations: [fea('human legal gate')],
  },
  {
    id: 'L-form',
    lintRuleId: 'phrase-length',
    title: 'Phrase shape',
    body: 'Contest ballads often breathe in phrase groups that feel like 3, 5, or 7 — worth noticing, not forced.',
    glossaryIds: [],
    citations: [bam('form / song selection')],
  },
  // Ranking factors
  {
    id: 'L-f-motion',
    factorId: 'motion',
    title: 'Motion score',
    body: 'Approach Three motion toward the pillar (or springboard freedom) raises this candidate.',
    glossaryIds: ['circle_fifths', 'springboard'],
    citations: [bam('Approach Three')],
  },
  {
    id: 'L-f-primary',
    factorId: 'primaryLayer',
    title: 'Primary layer',
    body: 'PCF on the pillar root keeps the structural story clear versus passing color.',
    glossaryIds: ['pcf', 'pillar'],
    citations: [bam('Approach Two')],
  },
  {
    id: 'L-f-seventh',
    factorId: 'seventh',
    title: 'Barbershop seventh bias',
    body: 'BS7 is the most characteristic ringing four-note chord in the style.',
    glossaryIds: ['bs7', 'lock_ring'],
    citations: [ryl('BS7')],
  },
  {
    id: 'L-f-closed',
    factorId: 'closedVoicing',
    title: 'Closed voicing',
    body: 'Compact spacing usually blends more easily than wide spreads.',
    glossaryIds: ['ttbb'],
    citations: [bam('voicing types')],
  },
  {
    id: 'L-f-ring',
    factorId: 'ring',
    title: 'Ring tier',
    body: 'Some natures lock more readily than others in the eleven-chord model.',
    glossaryIds: ['lock_ring'],
    citations: [ryl('ring ranking')],
  },
  {
    id: 'L-f-secdom',
    factorId: 'secondaryDominant',
    title: 'Secondary dominant',
    body: 'A BS7 a fifth above the next pillar drives the harmony home.',
    glossaryIds: ['secondary_dom'],
    citations: [bam('Rule 1'), pri('secondary dominants')],
  },
  {
    id: 'L-f-augpen',
    factorId: 'augDimPrimaryPenalty',
    title: 'Aug/dim penalty',
    body: 'Augmented and long diminished color fight lock when used as primary harmony.',
    glossaryIds: ['pillar'],
    citations: [ryl('aug / dim7')],
  },
  {
    id: 'L-f-harm',
    factorId: 'harmonicity',
    title: 'Harmonicity',
    body: 'Estimated partial coincidence under just ratios — higher often means better lock potential.',
    glossaryIds: ['ji', 'lock_ring'],
    citations: [ryl('JI model')],
  },
  {
    id: 'L-f-vl',
    factorId: 'voiceLead',
    title: 'Voice-leading distance',
    body: 'Smaller total motion in tenor/bari/bass between stacks usually sings cleaner. Melody (lead) leaps required by the tune are not penalized.',
    glossaryIds: ['ttbb'],
    citations: [bam('VL cost')],
  },
  {
    id: 'L-f-sv',
    factorId: 'strongVoice',
    title: 'Strong lead role',
    body: 'Lead chord-tone role (especially 3 or 7 on dominants) affects how strongly the stack “sings.”',
    glossaryIds: ['strong_voicing'],
    citations: [pri('strong voicing')],
  },
  {
    id: 'L-spacing',
    lintRuleId: 'theory-spacing',
    title: 'Series spacing',
    body: 'Space wider at the bottom and tighter on top — muddy low thirds and tenor/lead holes fight lock.',
    glossaryIds: ['harmonic_series_spacing', 'ttbb'],
    citations: [bam('voicing')],
  },
  {
    id: 'L-tension',
    lintRuleId: 'theory-tension',
    title: 'Resolve the dominant',
    body: 'When a BS7 moves on, its 3rd wants to rise and its ♭7 wants to fall — that is tension releasing.',
    glossaryIds: ['tension_release', 'leading_tone', 'active_seventh', 'bs7'],
    citations: [bam('harmony')],
  },
  {
    id: 'L-bs7-density',
    lintRuleId: 'bs7-density',
    title: 'About 30% sevenths',
    body: 'Contest barbershop character often needs a solid share of dominant sevenths — aim near thirty percent or more.',
    glossaryIds: ['bs7', 'tension_release'],
    citations: [pri('style'), bam('Strengthen')],
  },
  {
    id: 'L-f-tension',
    factorId: 'tensionRelease',
    title: 'Tension / release bias',
    body: 'Candidates that build dominant tension toward a pillar (or release on it) score higher.',
    glossaryIds: ['tension_release', 'secondary_dom'],
    citations: [bam('Approach Three')],
  },
  {
    id: 'L-f-resolution',
    factorId: 'resolution',
    title: 'Active-tone resolution',
    body: 'Voicings that continue a previous dominant’s 3↑ / ♭7↓ by step are preferred.',
    glossaryIds: ['tension_release', 'leading_tone'],
    citations: [bam('harmony')],
  },
  {
    id: 'L-f-spacing',
    factorId: 'spacing',
    title: 'Spacing score',
    body: 'Harmonic-series-like spacing (wide bass gap, compact upper voices) ranks higher.',
    glossaryIds: ['harmonic_series_spacing'],
    citations: [bam('voicing')],
  },
  {
    id: 'L-f-contrary',
    factorId: 'contrary',
    title: 'Contrary motion',
    body: 'Bass moving opposite the upper unit usually yields a fuller succession.',
    glossaryIds: ['contrary_motion'],
    citations: [bam('voice leading')],
  },
  {
    id: 'L-f-common',
    factorId: 'commonTone',
    title: 'Common-tone hold',
    body: 'Shared pitch classes kept in the same voice reduce unnecessary leaps.',
    glossaryIds: ['common_tone'],
    citations: [bam('voice leading')],
  },
  {
    id: 'L-f-parallel',
    factorId: 'parallelPenalty',
    title: 'Parallel penalty',
    body: 'Parallel perfect fifths/octaves or all parts leaping the same way are soft-penalized.',
    glossaryIds: ['parallel_5_8'],
    citations: [bam('voice leading')],
  },
]

/** key-suggestion shares lead-range lesson */
export const LINT_LESSON_ALIASES: Readonly<Record<string, string>> = {
  'key-suggestion': 'lead-range',
  'aug-many': 'aug-pillar',
  'dim-sustain': 'R4_dim7',
  'swipe-opportunity': 'step7_variety',
  'unconfirmed-pillars': 'step2_confirm',
  'no-pillars': 'step1_roots',
  'no-melody': 'melody',
  'missing-pillar': 'step1_roots',
  'song-eligibility': 'lead-range',
  'harmonic-motion': 'R1_p5',
  'homophony-density': 'few-sevenths',
  'bs7-density-duration': 'bs7-density',
  'dim7-chain': 'R4_dim7',
  'counterpart-flicker': 'R3_tritone',
  'aug-usage': 'aug-pillar',
}

/**
 * Lint ruleIds that are informational / structural and intentionally have no Learn lesson
 * (or only via alias above). Empty — prefer aliases; keep for future human-only gates.
 */
export const HUMAN_ONLY_LINT_RULE_IDS: readonly string[] = []
